"use client";

import { type ChangeEvent, useMemo, useState } from "react";

import AttributeAllocation from "@/components/character/AttributeAllocation";
import CreationSummary from "@/components/character/CreationSummary";
import SkillAllocation from "@/components/character/SkillAllocation";
import { changeAttributeAtCreation, changeSkillAtCreation, finalizeCharacterCreation, validateCharacterCreation } from "@/lib/characterCreation";
import { setActiveCharacterId, upsertCharacter } from "@/lib/storage";
import { createEmptyCharacter, type AttributeName, type Character } from "@/types/character";

interface CharacterCreatorProps { initialCharacter?: Character; onSaved?: (character: Character) => void; }

export default function CharacterCreator({ initialCharacter, onSaved }: CharacterCreatorProps) {
  const [character, setCharacter] = useState<Character>(() => initialCharacter ?? createEmptyCharacter());
  const [photoSource, setPhotoSource] = useState(""); const [photoError, setPhotoError] = useState("");
  const validation = useMemo(() => validateCharacterCreation(character), [character]);
  const update = (change: (current: Character) => Character) => setCharacter((current) => change(current));
  const setIdentity = (field: "name" | "player" | "role" | "level", value: string | number) => update((current) => ({ ...current, identity: { ...current.identity, [field]: value } }));
  function usePhotoUrl() { update((current) => ({ ...current, identity: { ...current.identity, photoUrl: photoSource.trim() || undefined } })); setPhotoSource(""); setPhotoError(""); }
  function handlePhotoFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/") || file.size > 1_500_000) { setPhotoError("Use uma imagem de até 1,5 MB."); return; } const reader = new FileReader(); reader.onload = () => { const photoUrl = typeof reader.result === "string" ? reader.result : undefined; update((current) => ({ ...current, identity: { ...current.identity, photoUrl } })); setPhotoError(""); }; reader.readAsDataURL(file); }
  function saveCharacter() { if (!validation.valid) return; const finalized = finalizeCharacterCreation({ ...character, identity: { ...character.identity, name: character.identity.name.trim() } }); setCharacter(finalized); upsertCharacter(finalized); setActiveCharacterId(finalized.id); onSaved?.(finalized); }
  return <main className="creator-shell"><header className="creator-header"><p className="eyebrow">Cyberpunk RED Toolkit</p><h1>Crie sua ficha.</h1><p>Distribua os pontos de criação. Eles deixam de existir quando a ficha é finalizada.</p></header><CreationSummary character={character} /><section className="creator-grid"><div className="creator-card identity-card"><div className="section-heading"><span>01</span><h2>Identidade</h2></div><div className="photo-row"><div className="photo-preview">{character.identity.photoUrl ? <img src={character.identity.photoUrl} alt="Prévia do personagem" /> : <span>SEM FOTO</span>}</div><div className="photo-controls"><label className="file-button">Enviar foto<input type="file" accept="image/*" onChange={handlePhotoFile} /></label><label className="field-label" htmlFor="photo-url">ou cole uma URL</label><div className="url-row"><input id="photo-url" value={photoSource} onChange={(event) => setPhotoSource(event.target.value)} placeholder="https://..." /><button type="button" className="secondary-button" onClick={usePhotoUrl}>Usar</button></div>{photoError && <p className="form-error">{photoError}</p>}</div></div><div className="identity-fields"><label><span>Nome</span><input value={character.identity.name} onChange={(event) => setIdentity("name", event.target.value)} placeholder="Zuberi Akil" /></label><label><span>Jogador</span><input value={character.identity.player} onChange={(event) => setIdentity("player", event.target.value)} placeholder="Seu nome" /></label><label><span>Função / Role</span><input value={character.identity.role} onChange={(event) => setIdentity("role", event.target.value)} placeholder="Solo" /></label><label><span>Nível</span><input type="number" min="1" max="10" value={character.identity.level} onChange={(event) => setIdentity("level", Math.max(1, Number(event.target.value) || 1))} /></label></div></div><div className="creator-card attributes-card"><div className="section-heading"><span>02</span><h2>Atributos</h2></div><AttributeAllocation character={character} onChange={(attribute: AttributeName, delta) => update((current) => changeAttributeAtCreation(current, attribute, delta))} /></div></section><section className="creator-card skills-card"><div className="section-heading"><span>03</span><h2>Perícias</h2></div><p className="helper-text">Concentração e Percepção já receberam seus mínimos obrigatórios, descontados do mesmo pool de perícias.</p><SkillAllocation character={character} onChange={(id, delta) => update((current) => changeSkillAtCreation(current, id, delta))} /></section><footer className="creator-footer"><p>{validation.valid ? "Ficha válida para criação." : "Corrija as pendências acima para criar o personagem."}</p><button type="button" className="save-button" onClick={saveCharacter} disabled={!validation.valid}>Criar personagem</button></footer></main>;
}